package(
    default_testonly = 1,
    default_visibility = ["//src/test/java:__subpackages__"],
)

java_library(
    name = "FakeStorageRpc2",
    srcs = ["FakeStorageRpc2.java"],
    deps = [
        "@maven//:com_google_apis_google_api_services_storage",
        "@maven//:com_google_cloud_google_cloud_nio",
        "@maven//:com_google_cloud_google_cloud_storage",
        "@maven//:com_google_http_client_google_http_client",
    ],
)
