name: Java CI
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v2
      with:
        cache: maven
        distribution: adopt
        java-version: 11
    - name: Test
      run: mvn --batch-mode --show-version test
