name: Java CI
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      MVN_FLAGS: --batch-mode --show-version
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        cache: maven
        distribution: adopt
        java-version: 11
    - name: make ci
      run: make ci
