name: Java CI
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Resolve dependencies
      run: mvn --batch-mode --show-version dependency:resolve dependency:resolve-plugins
    - name: Run tests
      run: mvn --batch-mode --show-version test
